from tkinter import *
root=Tk()
root.title("Usage of GUI based menu in GUI Python program")
root.minsize(1280,720)
menu1=Menu(root)
root.config(menu=menu1)
filemenu=Menu(menu1)
menu1.add_cascade(label='File', menu=filemenu)
filemenu.add_command(label='New')
filemenu.add_command(label='Open..')
filemenu.add_separator()
filemenu.add_command(label='Close Menu', command=filemenu.quit)
filemenu.add_command(label='Exit', command=root.quit)
helpmenu=Menu(menu1)
menu1.add_cascade(label='Help',menu=helpmenu)
helpmenu.add_command(label='About this program')
mainloop()
